### PR TITLE
Fix: MPI-Distribution w/o SC

### LINKED ISSUE #503: MPI Domain-Decomposition w/o Space Charge
Yesterday, I realized that domain decomposition and load balancing with MPI is broken when space charge is not used. All particles end up on the same MPI rank now, causing load imbalance. Need to investigate.

Seems to show up as an issue for N>2 ranks or so, because on `ResizeMesh` we pad the beam by 3x vacuum by default for dynamic mesh resizes.

Related to #498, but likely earlier caused by #181 / #261 / #367 / #402.

### PR DESCRIPTION
**Pull request by ax3l**
Without space charge, we can simply split the particles up during init in equal chunks and leave them there forever.

This fixes grid generation by setting the `max_grid_size` to the AMReX `blocking_factor` (if not set by the user). Also, this avoids all calls to `ResizeMesh()` and `Redistribute` for now.

Fix #503

### CODE REVIEW

File: src/ImpactX.cpp [hunk 1]
```diff
@@ -220,6 +226,19 @@ namespace impactx
...
+                    {
+                        // Resize the mesh, based on `m_particle_container` extent
+                        amrex::ParmParse pp_geometry("geometry");
+                        amrex::Vector<amrex::Real> prob_relative(max_level + 1, 1.0);
+                        pp_geometry.addarr("prob_relative", prob_relative);
+
+                        ResizeMesh();
+
+                        // Redistribute particles in the new mesh in x, y, t
+                        m_particle_container->Redistribute();
```
Comment (ax3l) [inline src/ImpactX.cpp]: Currently, this slightly looses particles over time.
We could and maybe should find a solution for this, so we can use this later on for load balancing, e.g., if we create secondaries or loose particles (e.g., to apertures/collimators).

File: src/particles/elements/diagnostics/openPMD.cpp [hunk 2]
```diff
@@ -318,7 +318,17 @@ namespace detail
 
         // pinned memory copy
         PinnedContainer pinned_pc = pc.make_alike<amrex::PinnedArenaAllocator>();
+
+        // FIXME: Looks like this only copies particles on rank 0...
+        auto const global_np_before = pc.TotalNumberOfParticles(true, false);
+        auto const local_np_before = pc.TotalNumberOfParticles(true, true);
         pinned_pc.copyParticles(pc, true);  // no filtering
```
Comment (ax3l) [inline src/particles/elements/diagnostics/openPMD.cpp]: @atmyers hm, that is confusing: it only copies particles on rank 0 (if we never redistribute and operate on a non-OK() container w/o space charge grid)

File: src/particles/ImpactXParticleContainer.cpp [hunk 3]
```diff
@@ -124,7 +125,19 @@ namespace impactx
...
+        {
+            const auto& pmap = ParticleDistributionMap(lid).ProcessorMap();
+            auto it = std::find(pmap.begin(), pmap.end(), amrex::ParallelDescriptor::MyProc());
+            if (it == std::end(pmap)) {
+                amrex::Abort("Attempting to add particles to box that does not exist.");
+            } else {
+                gid = *it;
+            }
+        }
+        auto& particle_tile = DefineAndReturnParticleTile(lid, gid, tid);
```
Comment (ax3l) [inline src/particles/ImpactXParticleContainer.cpp:139]: @atmyers @WeiqunZhang for `ParIter` loops after initialization, with OpenMP parallelism, does it matter which `tid` we use?

Or will be have now always one tile and no on-rank parallelism?

Comment (ax3l) [reply src/particles/ImpactXParticleContainer.cpp:139]: (Please note we never call `pc.Redistribute()` in this mode)
