### PR TITLE
Fix CUDA Shutdown of Element Dynamic Data

### LINKED ISSUE #911: RFCavity: Clean GPU Shutdown
There is currently a shutdown issue in tests like `FODO.rf.sc.run`, e.g., for the `RFCavity`, `SoftQuad` and `SoftSol` element, that throw an issue on sim shutdown:
```
AMReX (25.03) finalized
pure virtual method called
terminate called without an active exception
Aborted (core dumped)
```

Full backtrace from `cuda-gdb`:
```
0x00007fffdca9eb2c in pthread_kill () from /lib/x86_64-linux-gnu/libc.so.6
(cuda-gdb) bt
#0  0x00007fffdca9eb2c in pthread_kill () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007fffdca4527e in raise () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007fffdca288ff in abort () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x00007ffff16d4fbe in __gnu_cxx::__verbose_terminate_handler () at ../../../../libstdc++-v3/libsupc++/vterminate.cc:95
#4  0x00007ffff16d3502 in __cxxabiv1::__terminate (handler=<optimized out>) at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:48
#5  0x00007ffff16cd303 in std::terminate () at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:58
#6  0x00007ffff16d4013 in __cxa_pure_virtual () at ../../../../libstdc++-v3/libsupc++/pure.cc:50
#7  0x0000555555637466 in amrex::ArenaAllocatorBase<double, amrex::ArenaWrapper>::deallocate (this=0x555566020cc8, 
    ptr=0x7fffa6611790) at /home/axel/src/impactx/build/_deps/fetchedamrex-src/Src/Base/AMReX_GpuAllocators.H:60
#8  amrex::ArenaAllocatorBase<double, amrex::ArenaWrapper>::deallocate (ptr=0x7fffa6611790, this=0x555566020cc8)
    at /home/axel/src/impactx/build/_deps/fetchedamrex-src/Src/Base/AMReX_GpuAllocators.H:58
#9  amrex::PODVector<double, amrex::ArenaAllocator<double> >::~PODVector (this=0x555566020cc8, __in_chrg=<optimized out>)
    at /home/axel/src/impactx/build/_deps/fetchedamrex-src/Src/Base/AMReX_PODVector.H:360
#10 std::pair<int const, amrex::PODVector<double, amrex::ArenaAllocator<double> > >::~pair (this=0x555566020cc0, 
    __in_chrg=<optimized out>)
    at /home/axel/micromamba/envs/warpx-gpu-mpich-dev/lib/gcc/x86_64-conda-linux-gnu/13.3.0/include/c++/bits/stl_pair.h:187
#11 std::__new_allocator<std::_Rb_tree_node<std::pair<int const, amrex::PODVector<double, amrex::ArenaAllocator<double> > > > >::destroy<std::pair<int const, amrex::PODVector<double, amrex::ArenaAllocator<double> > > > (__p=0x555566020cc0, this=<optimized out>)
    at /home/axel/micromamba/envs/warpx-gpu-mpich-dev/lib/gcc/x86_64-conda-linux-gnu/13.3.0/include/c++/bits/new_allocator.h:198
#12 std::allocator_traits<std::allocator<std::_Rb_tree_node<std::pair<int const, amrex::PODVector<double, amrex::ArenaAllocator<double> > > > > >::destroy<std::pair<int const, amrex::PODVector<double, amrex::ArenaAllocator<double> > > > (__p=0x555566020cc0, __a=...)
    at /home/axel/micromamba/envs/warpx-gpu-mpich-dev/lib/gcc/x86_64-conda-linux-gnu/13.3.0/include/c++/bits/alloc_traits.h:558
#13 std::_Rb_tree<int, std::pair<int const, amrex::PODVector<double, amrex::ArenaAllocator<double> > >, std::_Select1st<std::pair<int const, amrex::PODVector<double, amrex::ArenaAllocator<double> > > >, std::less<int>, std::allocator<std::pair<int const, amrex::PODVector<double, amrex::ArenaAllocator<double> > > > >::_M_destroy_node (__p=0x555566020ca0, this=<optimized out>)
    at /home/axel/micromamba/envs/warpx-gpu-mpich-dev/lib/gcc/x86_64-conda-linux-gnu/13.3.0/include/c++/bits/stl_tree.h:625
#14 std::_Rb_tree<int, std::pair<int const, amrex::PODVector<double, amrex::ArenaAllocator<double> > >, std::_Select1st<std::pair<int const, amrex::PODVector<double, amrex::ArenaAllocator<double> > > >, std::less<int>, std::allocator<std::pair<int const, amrex::PODVector<double, amrex::ArenaAllocator<double> > > > >::_M_drop_node (this=<optimized out>, __p=0x555566020ca0)
    at /home/axel/micromamba/envs/warpx-gpu-mpich-dev/lib/gcc/x86_64-conda-linux-gnu/13.3.0/include/c++/bits/stl_tree.h:633
#15 std::_Rb_tree<int, std::pair<int const, amrex::PODVector<double, amrex::ArenaAllocator<double> > >, std::_Select1st<std::pair<int const, amrex::PODVector<double, amrex::ArenaAllocator<double> > > >, std::less<int>, std::allocator<std::pair<int const, amrex::PODVector<double, amrex::ArenaAllocator<double> > > > >::_M_erase (__x=0x555566020ca0, this=<optimized out>)
    at /home/axel/micromamba/envs/warpx-gpu-mpich-dev/lib/gcc/x86_64-conda-linux-gnu/13.3.0/include/c++/bits/stl_tree.h:1938
#16 0x0000555555637448 in std::_Rb_tree<int, std::pair<int const, amrex::PODVector<double, amrex::ArenaAllocator<double> > >, std::_Select1st<std::pair<int const, amrex::PODVector<double, amrex::ArenaAllocator<double> > > >, std::less<int>, std::allocator<std::pair<int const, amrex::PODVector<double, amrex::ArenaAllocator<double> > > > >::_M_erase (__x=0x555566021260, this=<optimized out>)
    at /home/axel/micromamba/envs/warpx-gpu-mpich-dev/lib/gcc/x86_64-conda-linux-gnu/13.3.0/include/c++/bits/stl_tree.h:789
--Type <RET> for more, q to quit, c to continue without paging--
#17 0x00007fffdca47a76 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#18 0x00007fffdca47bbe in exit () from /lib/x86_64-linux-gnu/libc.so.6
#19 0x00007fffdca2a1d1 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#20 0x00007fffdca2a28b in __libc_start_main () from /lib/x86_64-linux-gnu/libc.so.6
#21 0x000055555563711b in _start ()
```

Which points here:
https://github.com/AMReX-Codes/amrex/blob/25.03/Src/Base/AMReX_PODVector.H#L360

Could be a memory leak of the user-specified data arrays that we forget to cleanly free... and then it has issues deallocating after AMReX is finalized and the arenas are already torn down....?

### PR DESCRIPTION
**Pull request by ax3l**
Elements: The `finalize()` functions did not have access to our map yet, because we did not share global visibility between TUs. This fixes it using the C++17 guaranteed `inline` declaration.

Fix #911

### CODE REVIEW

File: src/elements/RFCavity.H [hunk 1]
```diff
@@ -89,17 +89,17 @@ namespace impactx::elements
...
     //! host: cosine coefficients in Fourier expansion of on-axis electric field Ez
-    static inline std::map<int, std::vector<amrex::ParticleReal>> h_cos_coef = {};
+    inline std::map<int, std::vector<amrex::ParticleReal>> h_cos_coef = {};
     //! host: sine coefficients in Fourier expansion of on-axis electric field Ez
-    static inline std::map<int, std::vector<amrex::ParticleReal>> h_sin_coef = {};
+    inline std::map<int, std::vector<amrex::ParticleReal>> h_sin_coef = {};
 
     //! device: cosine coefficients in Fourier expansion of on-axis electric field Ez
-    static inline std::map<int, amrex::Gpu::DeviceVector<amrex::ParticleReal>> d_cos_coef = {};
+    inline std::map<int, amrex::Gpu::DeviceVector<amrex::ParticleReal>> d_cos_coef = {};
```
Comment (ax3l) [inline src/elements/RFCavity.H:100]: Before this fix, accessing `d_cos_coef`/`d_sin_coef` in `finalize()` returned/operated on zero-`size()` maps, because these global variables were not properly shared between TUs.

File: src/particles/distribution/Thermal.H [hunk 2]
```diff
@@ -330,8 +330,8 @@ namespace distribution
         finalize ()
         {
             // deallocate
-            ThermalData::m_d_cdf1.clear();
-            ThermalData::m_d_cdf2.clear();
+            ThermalData::m_d_cdf1.release();
```
Comment (ax3l) [inline src/particles/distribution/Thermal.H]: As long as the `amrex::Gpu::DeviceVector` destructor is not called, there seems to be some arena memory left after a call to `.clear()`. This fixes the same shutdown issue as for the elements with array data.

Comment (ax3l) [reply src/particles/distribution/Thermal.H]: Will move this to a separate PR, because it seems to need more thought/testing: #915

File: src/elements/RFCavity.H [hunk 3]
```diff
@@ -89,17 +89,17 @@ namespace impactx::elements
 namespace RFCavityData
 {
     //! last used id for a created RF cavity
-    static inline int next_id = 0;
```
Comment (ax3l) [inline src/elements/RFCavity.H:92]: `static inline` is for class member variables. Here we are global vars in namespaces, where `static` limits visibility to the TU.
